// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf

package runtime

var Dyninstevent = newAsset("dyninst_event.c", "58803c95241e882112025aa829d4c1b1fb38f9d6ec600476ec2d74044b785b56")
