// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -I ../../network/ebpf/c -I ../c -fsigned-char types.go

package telemetry

type mapErrTelemetry struct {
	Count [64]uint64
}
type HelperErrTelemetry struct {
	Count [384]uint64
}
