// Code generated by genpost.go; DO NOT EDIT.

package protocols

import (
	"testing"

	"github.com/DataDog/datadog-agent/pkg/ebpf/ebpftest"
)

func TestCgoAlignment_Message(t *testing.T) {
	ebpftest.TestCgoAlignment[Message](t)
}
